version: '3.9'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
 
    volumes:
      - .:/usr/src/app
    ports:  
      - "8000:8000"
      - "5678:5678"

    # networks:
    #   - localnet

# networks:
#   localnet:
#     name: localnet
#     external: true